### ISSUE TITLE
百度无限302

### ISSUE THREAD

**Issue by kajweb** [yitd/Any-Proxy#1]

**Comment by yitd** [comment]
域名多少？伪静态问题吧



---原始邮件---
发件人: "-GITHUB OFFICIALS-"<notifications@github.com&gt;
发送时间: 2021年2月15日(周一) 凌晨4:23
收件人: "yitd/Any-Proxy"<Any-Proxy@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [yitd/Any-Proxy] 百度无限302 (#1)

**Comment by kajweb** [comment]
在测试地址直接输入 baidu.com

**Comment by yitd** [comment]
链接后面必须加http://才能访问



---原始邮件---
发件人: "-GITHUB OFFICIALS-"<notifications@github.com&gt;
发送时间: 2021年2月16日(周二) 中午1:52
收件人: "yitd/Any-Proxy"<Any-Proxy@noreply.github.com&gt;;
抄送: "yitd"<yitd@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [yitd/Any-Proxy] 百度无限302 (#1)




 
在测试地址直接输入 baidu.com
