### ISSUE TITLE
gbk网站会乱码

### ISSUE THREAD

**Issue by 5536086** [yitd/Any-Proxy#2]
gbk网站反代会乱码

**Comment by yitd** [comment]
倒数第六行添加：header("Content-Type:text/html;charset=gb2312");




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yitd/Any-Proxy"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月16日(星期二) 下午3:11
收件人:&nbsp;"yitd/Any-Proxy"<Any-Proxy@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[yitd/Any-Proxy] gbk网站会乱码 (#2)





 
gbk网站反代会乱码

**Comment by yitd** [comment]
gbk乱码问题已解决，自动转换

**Comment by 5536086** [comment]
大佬效率高，赞一个

**Comment by 5536086** [comment]
index_all.php，这个有问题，反代没反应

**Comment by yitd** [comment]
修改好了
